name: fungid_flutter
description: The App for Fungid.app
publish_to: 'none'
version: 0.0.10+10

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  fungid_api:
    path: packages/fungid_api
  local_db:
    path: packages/local_db
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  json_annotation: ^4.4.0
  path_provider: ^2.0.9
  path: '^1.8.0'
  image_picker: ^0.8.5
  openapi_generator_annotations: ^4.0.0
  uuid: ^3.0.6
  image: ^3.2.0
  shared_preferences: ^2.0.15
  carousel_slider: ^4.1.1
  geolocator: ^9.0.1
  geocoding: ^2.0.5
  google_maps_flutter: ^2.2.0
  rxdart: ^0.27.5
  bloc: ^8.1.0
  dio: '>=4.0.1 <5.0.0'
  built_collection: '>=5.1.0 <6.0.0'
  flutter_pretty_dio_logger: '2.0.2'
  firebase_core: ^1.22.0
  firebase_crashlytics: ^2.8.10
  url_launcher: ^6.1.5
  image_gallery_saver: ^1.7.1
  intl: ^0.17.0
  cached_network_image: ^3.2.2
  fl_chart: ^0.55.2
  flex_color_scheme: ^6.0.1
  connectivity_plus: ^2.3.9
  pytorch_mobile: ^0.2.2
  # pytorch_mobile_v2:
  #   git:
  #     url: https://github.com/fungid-app/flutter_pytorch_mobile
  #     ref: master # branch name

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.3
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  mocktail: ^0.2.0
  openapi_generator: ^4.0.0
  flutter_lints: ^2.0.0
  test: ^1.21.4
  freezed: ^2.0.5
  dependency_validator: ^3.2.2
  built_value: '>=8.1.0 <9.0.0'
  collection: ^1.16.0

# flutter_icons:
#   android: true
#   ios: true
#   image_path: 'assets/logo/icon.png'
#   remove_alpha_ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  assets:
    - assets/db/app.sqlite3
    - assets/models/

  uses-material-design: true
